default:
  image: algorithmiahq/sbt-builder:latest

stages:
- test
- publish

test:unit_test:
  stage: test
  script:
  - sbt test

publish:push_to_maven:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
  stage: publish
  script:
  - sbt ci-release
